Vagrant.configure("2") do |config|

	config.vm.define "master" do |master|
  		master.vm.box = "bento/ubuntu-16.04"
  		master.vm.provision :shell, path: "master.sh"
  		master.vm.network :private_network, ip: "172.16.1.4"

			master.vm.hostname = "manager"
			master.vm.provider "virtualbox" do |pmv|
				pmv.memory = 512
				pmv.cpus   = 1
			end
	end

	config.vm.define "client" do |client|
	  client.vm.box = "bento/ubuntu-16.04"
		client.vm.hostname = "client"
	  client.vm.provision :shell, path: "client.sh"
	  client.vm.network :private_network, ip: "172.16.1.5"
	end

	config.vm.define "splunk" do |splunk|
	  splunk.vm.box = "bento/ubuntu-16.04"
		splunk.vm.hostname = "splunk"
	  splunk.vm.provision :shell, path: "splunk.sh"
	  splunk.vm.network :private_network, ip: "172.16.1.6"
	end

	config.vm.define "agent2" do |agent2|
	  agent2.vm.box = "bento/ubuntu-16.04"
		agent2.vm.hostname = "agent2"
	  agent2.vm.provision :shell, path: "agent.sh"
	  agent2.vm.network :private_network, ip: "172.16.1.7"
	end

	config.vm.define "agent3" do |agent3|
	  agent3.vm.box = "bento/ubuntu-16.04"
		agent3.vm.hostname = "agent3"
	  agent3.vm.provision :shell, path: "agent.sh"
	  agent3.vm.network :private_network, ip: "172.16.1.8"
	end

end
