# -*- mode: ruby -*-
# vi: set ft=ruby :

master_ip = "172.16.1.4"
worker_ip = "172.16.1.5"
indexer_ip = "172.16.1.6"


Vagrant.configure("2") do |config|

	config.vm.define "master" do |master|
  		master.vm.box = "centos/7"
  		master.vm.provision :shell, path: "master.sh"
  		master.vm.network :private_network, ip: "#{master_ip}"

			master.vm.hostname = "manager"
			master.vm.provider "virtualbox" do |pmv|
				pmv.memory = 512
				pmv.cpus   = 1
			end
	end

	config.vm.define "client" do |client|
	  client.vm.box = "centos/7"
		client.vm.hostname = "client"
	  client.vm.provision :shell, path: "client.sh"
	  client.vm.network :private_network, ip: "#{worker_ip}"
	end

	config.vm.define "splunk" do |splunk|
	  splunk.vm.box = "centos/7"
		splunk.vm.hostname = "splunk"
	  splunk.vm.provision :shell, path: "splunk.sh"
	  splunk.vm.network :private_network, ip: "#{indexer_ip}"
	end
	# CentOS 7 agent instance
	config.vm.define "agent" do |agent|
	  agent.vm.box = "centos/7"
	  agent.vm.provision :shell, path: "agent-dev.sh"
	  agent.vm.network :private_network, ip: "172.16.1.7"
		agent.vm.provider "virtualbox" do |pmv|
			pmv.memory = 512
			pmv.cpus   = 1
	  end
	  agent.vm.hostname = "agent"
	end

	# Ubuntu 16 agent instance
	config.vm.define "agent-ubuntu" do |agent|
	  agent.vm.box = "centos/7"
	  agent.vm.provision :shell, path: "agent-pkg.sh"
	  agent.vm.network :private_network, ip: "172.16.1.8"
		agent.vm.provider "virtualbox" do |pmv|
			pmv.memory = 512
			pmv.cpus   = 1
	  end
	  agent.vm.hostname = "agent-ubuntu"
	end
end
