Vagrant.configure("2") do |config|

	config.vm.define "master" do |master|
  		master.vm.box = "centos/7"
  		master.vm.network :private_network, ip: "172.16.1.4"
			master.vm.provision :shell, path: "master.sh"
			master.vm.hostname = "manager"
			master.vm.provider "virtualbox" do |pmv|
				pmv.memory = 512
				pmv.cpus   = 1
			end
	end

	config.vm.define "client" do |client|
	  client.vm.box = "centos/7"
		client.vm.hostname = "client"
	  client.vm.provision :shell, path: "client.sh"
	  client.vm.network :private_network, ip: "172.16.1.5"
	end

	config.vm.define "agent2" do |agent2|
	  agent2.vm.box = "centos/7"
		agent2.vm.hostname = "agent2"
	  agent2.vm.provision :shell, path: "agent-pkg.sh"
	  agent2.vm.network :private_network, ip: "172.16.1.7"
	end

	config.vm.define "agent3" do |agent3|
	  agent3.vm.box = "centos/7"
		agent3.vm.hostname = "agent3"
	  agent3.vm.provision :shell, path: "agent-dev.sh"
	  agent3.vm.network :private_network, ip: "172.16.1.8"
	end

end
